version: '3'

services:
  web:
    container_name: webserver_flask_welcome
    build: .
    volumes:
      - .:/code
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_DATABASE_HOST: "redis"
    command: [ "gunicorn", "--bind", "0.0.0.0:5001", "--workers", "3", "main:flask_app" ]
    depends_on:
      - redis
    networks:
      - offertiamo_development_welcome
  redis:
    hostname: redis
    container_name: redis_db_welcome
    image: redis
    ports:
      - "6379"
    volumes:
      - ./data:/data
    networks:
      - offertiamo_development_welcome
networks:
  offertiamo_development_welcome:
