version: '3'
services:
  web:
    container_name: webserver_welcome_server
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: [ "gunicorn", "--bind", "0.0.0.0:5000", "--workers", "3", "main:flask_app" ]
    networks:
      - welcome_server_network

networks:
  welcome_server_network:
